# Following steps need to be run manually
# sudo curl -L -o /etc/yum.repos.d/gh-cli.repo https://cli.github.com/packages/rpm/gh-cli.repo
# sudo dnf install gh -y
# gh auth login -s admin:org

- name: Set a hostname
  ansible.builtin.hostname:
    name: github-runner

- name: Add github Runner User
  ansible.builtin.user:
    name: grunner

- name: Create a Directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: grunner
    group: grunner

- name: Extract and download Github-runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.328.0/actions-runner-linux-x64-2.328.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes
    owner: grunner
    group: grunner

- name: Configure the Github Runner
  ansible.builtin.shell: ./config.sh --url https://github.com/Batch02-2025/tools-automation-code --token BRQVJJNJHMEUAKIMVNLMJADIZU6RG --runnergroup Default --name ec2 --labels rhel --work _work --replace
  args:
    chdir: /actions-runner
  become: true
  become_user: github

- name: Update the path
  ansible.builtin.copy:
    src: path
    dest: /actions-runner/.path
    become_user: grunner

- name: Install Github Service
  ansible.builtin.shell: ./svc.sh install grunner; ./svc.sh start
  args:
    chdir: /actions-runner
    become_user: grunner

- name: Yum Utils Install
  ansible.builtin.shell: sudo yum install -y yum-utils
  args:
    chdir: /actions-runner
    become_user: grunner

- name: Copy the Terraform Repo File
  ansible.builtin.shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  args:
    chdir: /actions-runner
    become_user: grunner

- name: Install Terraform
  ansible.builtin.yum:
    name: terraform
    state: present

- name: Install python3.11-pip
  ansible.builtin.yum:
    name: python3.11-pip
    state: present

- name: Install Ansible using pip3.11
  ansible.builtin.pip:
    name: ansible
    executable: pip3.11



