# Configure using Ansible the Hashicorp Vault Server

- name: Set a hostname
  ansible.builtin.hostname:
    name: vault

- name: Yum Utils install
  ansible.builtin.shell: sudo yum install -y yum-utils

- name: Copy Repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  become: true
  ansible.builtin.yum:
    name: vault
    state: present

- name: Add Openbao User
  ansible.builtin.user:
    name: openbao

- name: Change Ownership for directory
  ansible.builtin.file:
    path: /var/lib/openbao
    owner: openbao
    group: openbao
    state: directory
    recurse: true

- name: Set permissions for a directory
  ansible.builtin.file:
    path: /var/lib/openbao
    state: directory
    mode: '0750'

- name: Copy Vault Config file
  ansible.builtin.copy:
    src: openbao.hcl
    dest: /etc/openbao.d/openbao.hcl
    mode: '0644'

- name: Start Vault service
  ansible.builtin.service:
    name: vault
    state: started
    enabled: true
