name: Provision Tool Infra
on:
  workflow_dispatch:
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the latest Terraform version
      - name: Install Terraform (latest)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false   # optional, for raw CLI output

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
